#FIND_PATH(FESTIVAL_INCLUDE_DIR foo.h /usr/include/foo /usr/local/include/foo)

FIND_PATH(FESTIVALL_LIBRARY NAMES el_diphone.scm PATH /usr/share/festival/voices/spanish/el_diphone/festbox) 

IF (FESTIVALL_LIBRARY)
   SET(FESTIVALL_FOUND TRUE)
ENDIF (FESTIVALL_LIBRARY)


IF (FESTIVALL_FOUND)
   IF (NOT FESTIVALL_FIND_QUIETLY)
	    MESSAGE(STATUS "Found FESTIVALL LANG: ${FESTIVALL_LIBRARY}")
   ENDIF (NOT FESTIVALL_FIND_QUIETLY)
ELSE (FESTIVALL_FOUND)
   IF (Festivallan_FIND_REQUIRED)
      MESSAGE(FATAL_ERROR "Could not find FESTIVALL LANG, instalar festvox-ellpc11k")
   ENDIF (Festivallan_FIND_REQUIRED)
ENDIF (FESTIVALL_FOUND)
