#FIND_PATH(SOX_INCLUDE_DIR foo.h /usr/include/foo /usr/local/include/foo)

FIND_FILE(SOX_LIBRARY NAMES sox PATH /usr/bin) 

IF (SOX_LIBRARY)
   SET(SOX_FOUND TRUE)
ENDIF (SOX_LIBRARY)


IF (SOX_FOUND)
   IF (NOT SOX_FIND_QUIETLY)
	    MESSAGE(STATUS "Found SOX: ${SOX_LIBRARY}")
   ENDIF (NOT SOX_FIND_QUIETLY)
ELSE (SOX_FOUND)
   IF (Sox_FIND_REQUIRED)
      MESSAGE(FATAL_ERROR "Could not find SOX, instalar sox")
   ENDIF (Sox_FIND_REQUIRED)
ENDIF (SOX_FOUND)

